### ISSUE TITLE
Lite-HRNet does not perform well in the bottom-up pose estimation task 

### ISSUE THREAD

**Issue by xiexiaoshinick** [HRNet/Lite-HRNet#13]
This is a great job. 
I use LIte-HRNet as the backbone to reproduce [HigherHRNet-Human-Pose-Estimation](https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation) 
but the result is not very satisfactory. 
I hope you can provide useful suggestions. 
Thank you for your work. 
![image](https://user-images.githubusercontent.com/26023731/115361842-8d9e0380-a1f3-11eb-8bf4-5b48e86a2124.png)
![image](https://user-images.githubusercontent.com/26023731/115363262-e15d1c80-a1f4-11eb-913b-62182367886a.png)
Do you have plans to test the **bottom-up pose-estimation** task?

**Comment by yu-changqian** [comment]
Thanks for your experiments.
We haven't try it on the bottom-up method.
Maybe after trying, we can make some discussions on this idea.

**Comment by welleast** [comment]
https://github.com/HRNet/DEKR is a recently-developed bottom-up method. It might be choice to try Lite-HRNet in DEKR.

**Comment by huixiancheng** [comment]
Hi!
Can your network converge fast , I used it on semantic segmentation and found that the loss convergence speed is very slow(compare with other backbone)
