### ISSUE TITLE
different from another hrnet

### ISSUE THREAD

**Issue by neosoob** [HRNet/Lite-HRNet#14]
https://github.com/HRNet/Lite-HRNet/blob/0ff756074c199ae3bd06fb651019bd151b33142e/models/backbones/litehrnet.py#L634

https://github.com/HRNet/HRNet-Semantic-Segmentation/blob/f9fb1ba66ff8aea29d833b885f08df64e62c2b23/lib/models/hrnet.py#L264

https://github.com/HRNet/HRNet-Human-Pose-Estimation/blob/00d7bf72f56382165e504b10ff0dddb82dca6fd2/lib/models/pose_hrnet.py#L258

https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/aa23881492ff511185acf756a2e14725cc4ab4d7/lib/models/pose_higher_hrnet.py#L236

yours: for j in range(self.num_branches):

others: for j in range(1, self.num_branches):

should the range be (1, self.num_branches) ?

**Comment by neosoob** [comment]
https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/aa23881492ff511185acf756a2e14725cc4ab4d7/lib/models/pose_higher_hrnet.py#L236

the range in higherhrnet is also (1, self.num_branches)

**Comment by yu-changqian** [comment]
Thanks for pointing it out. We will fix this issue and update the code. In my opinion, this will not affect the results.
