### ISSUE TITLE
Where is "Topdown" type?

### ISSUE THREAD

**Issue by ronghui19** [HRNet/Lite-HRNet#17]
`model = dict(
    type='Topdown',
    # num_stages=3,
    pretrained=None,
    backbone=dict(
        type='LiteHRNet',
        in_channels=3,
        extra=dict(
            stem=dict(
                stem_channels=32,
                out_channels=32,
                expand_ratio=1),
            num_stages=3,
            stages_spec=dict(
                num_modules=(3, 8, 3),
                num_branches=(2, 3, 4),
                num_blocks=(2, 2, 2),
                module_type=('LITE', 'LITE', 'LITE'),
                with_fuse=(True, True, True),
                reduce_ratios=(8, 8, 8),
                num_channels=(
                    (40, 80),
                    (40, 80, 160),
                    (40, 80, 160, 320),
                )),
            with_head=False,
        )),`

any ideas about how to find out "Topdown"?

**Comment by yu-changqian** [comment]
Hello, this project is based on mmpose. Therefore, the `Topdown` pose detector is defined in [here](https://github.com/open-mmlab/mmpose/blob/master/mmpose/models/detectors/top_down.py).
