### ISSUE TITLE
will the semantic segmentation code release?

### ISSUE THREAD

**Issue by zhangyunming** [HRNet/Lite-HRNet#2]
hi, it seems lite-hrnet semantic segmentation has higher precision than your bisenetv2. will the code relase. wait in hope.

**Comment by yu-changqian** [comment]
Thanks for your attention.
The segmentation codes are being re-organized and cleaned. 
We will release the segmentation codes of the Lite-HRNet ASAP.

**Comment by nsapkota417** [comment]
Waiting for LiteHRNet Semantic Segmentation code. :)
