### ISSUE TITLE
died with <Signals.SIGSEGV: 11>

### ISSUE THREAD

**Issue by qbTrible** [HRNet/Lite-HRNet#28]
Hi, Thanks your work! When I train with dist_train.sh, the error reported as follows, 
![image](https://user-images.githubusercontent.com/41276778/117524474-f78a1b80-afef-11eb-9988-770c5b5f5548.png)

**Comment by yu-changqian** [comment]
It looks like an issue of the distributed training for mmpose. Maybe you could report it on the mmpose project?
