### ISSUE TITLE
安装ERRORS

### ISSUE THREAD

**Issue by WangChen100** [HRNet/Lite-HRNet#9]
1. requirment.txt要求安装numpy=1.19.0，但会报错“ValueError: numpy.ndarray size changed, may indicate binary incompatibility
”
解决方法：版本问题，安装numpy 1.20.0
pip install numpy==1.20.0

2. 缺少mmpose包，要最近新版的，否则会缺少相应模块，如NECKS
git clone git@github.com:open-mmlab/mmpose.git
cd mmpose
pip install -r requirements.txt
python setup.py develop

3. ModuleNotFoundError: No module named 'poseval'
git clone https://github.com/svenkreiss/poseval.git
cd poseval
pip install -e . 

4. ModuleNotFoundError: No module named 'tensorboard'
pip install future tensorboard

**Comment by yu-changqian** [comment]
Thanks for your attention.
The modules of MMPose Future Tensorboard are in [requirements/runtime.txt](https://github.com/HRNet/Lite-HRNet/blob/hrnet/requirements/runtime.txt).
Poseeval is in [requirements/optional.txt](https://github.com/HRNet/Lite-HRNet/blob/hrnet/requirements/optional.txt).
They could be installed according to the tutorial if there is no problems with the environments.

**Comment by wangm-word** [comment]
你好，这是windows安装mmpose吗
